# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-06-14 14:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0029_auto_20210202_1627'),
    ]

    operations = [
        migrations.CreateModel(
            name='imio_atal',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('title', models.CharField(max_length=50, verbose_name='Title')),
                ('slug', models.SlugField(unique=True, verbose_name='Identifier')),
                ('description', models.TextField(verbose_name='Description')),
                (
                    'base_url',
                    models.URLField(
                        help_text='API base URL',
                        max_length=256,
                        verbose_name='Base URL',
                    ),
                ),
                ('api_key', models.CharField(max_length=128, verbose_name='API Key')),
                (
                    'users',
                    models.ManyToManyField(
                        blank=True,
                        related_name='_imio_atal_users_+',
                        related_query_name='+',
                        to='base.ApiUser',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Connecteur Atal (iMio)',
            },
        ),
    ]
